app/urls.py
from django.urls import path
from.import views
from app import api
from django.contrib import admin
from django.conf import settings
#from .views import attendancelist
from .views import CustomLogoutView
from django.urls import reverse_lazy
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_view

from django.shortcuts import render
from django.conf.urls import handler404

# def custom_404(request, exception):
#     return render(request, 'errors/404.html', status=404)


# # views.py
# from django.http import HttpResponse

# def trigger_error(request):
#     division_by_zero = 1 / 0  
#     return HttpResponse("This won't be reached")


# def custom_500(request):
#     return render(request, 'errors/500.html', status=500)

# handler404 = custom_404
# handler500 = custom_500



urlpatterns = [

#----------------------------------------------------------- Dharshini --------------------------------------------------------------------------

    path('login/', views.login_admin, name='login'), 
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('', views.index, name='index'),

#---------------------------- UOM ----------------------------

    path('uom/', views.uom, name='uom'),
    path('add-uom/', views.add_uom, name='add-uom'),
    path('update-uom/<int:pk>/', views.update_uom, name='update-uom'),
    path('delete-uom/<int:pk>/', views.delete_uom, name='delete-uom'),

    # path('uom/', views.uom, name='uom') ,            
    # path('get_data/<int:id>/', views.get_data, name='get_data'),
    # path('delete_uom/<int:id>/', views.delete_uom, name='delete_uom'),
    # path('save_data/<int:id>/', views.save_data, name='save_data'),

#------------------------ Company Staff --------------------

    path('process-status', views.get_process_status, name='process-status'),

#---- Employee Role ----

    path('emproles/',views.emproles, name="emproles"),           
    path('add_emproles/',views.add_emproles, name="add-emproles"), 
    path('update_emproles/<int:id>/',views.update_emproles, name="update-emproles"), 
    path('get_emproles/<int:id>/', views.get_emproles, name='get_emproles'),
    path('delete_emproles/<int:id>/', views.delete_emproles, name='delete_emproles'),
    # path('save_emproles/<int:id>/', views.save_emproles, name='save_emproles'),

#---- Employee ----

    path('employee/',views.employee,name= 'employee'),          
    path('get_employee/<int:id>/', views.get_employee, name='get_employee'),
    path('delete_employee/<int:id>/', views.delete_employee, name='delete_employee'),
    path('save_employee/<int:id>/', views.save_employee, name='save_employee'),

#-------------------------- Purchases --------------------

#----- Vendor Registration -----

    path('vendor/', api.vendor, name='vendors'),
    path('vendor-list/', api.vendor_list, name='vendors-list'),
    path('add_vendor/', api.add_vendor, name='add_vendor'),
    path('update_vendor/<int:pk>/', api.update_vendor, name='update_vendor'),
    path('delete_vendor/<int:pk>/', api.delete_vendor, name='delete_vendor'),

#----- Vendor Quatation -----

    path('vendorquatation/', api.vendorquatation, name='vendorquates'),
    path('add_vendorquatation/', api.add_vendorquatation, name='add_vendorquatation'),
    path('update_vendorquatation/<int:pk>/', api.update_vendorquatation, name='update_vendorquatation'),
    path('delete_vendorquatation/<int:pk>/', api.delete_vendorquatation, name='delete_vendorquatation'),

#----- Add Purchase -----

    path('purchase/',api.purchase, name="purchase"),
    path('purchase-list/<str:pk>/',views.purchase_list, name="purchase-ist"),
    path('add_purchase/', api.add_purchase, name='add_purchase'),

#----- Purchase List -----

    path('purchaselist/',api.purchaselist,name='purchaselist'), 

    path('project-purchase-history/<int:pk>/',api.project_purchaselist,name='project-purchase-history'),
    path("purchase-status-change/<int:pk>/",api.purchase_status_change, name = 'purchase-status-change') ,
    # path('purchase-filter/<str:pk>/', api.purchase_filter, name="purchase_filter"),

#-------------------------- Quatation --------------------

# #----- Add Quatation -----

#     path('quatation/',api.quatation, name="quatation"),
#     path('add_quatation/',api.add_quatation, name='add_quatation'),

# #----- Quatation List -----

#     path('quatation-payment/<str:pk>/', api.quatation_payment, name="quatation-payment"),
#     path('quatation-payment-date/<int:pk>/', api.quatation_payment_date, name="quatation-payment_date"),

#------------------- Inventory Management ----------------

    path('inventory/',api.inventory, name="inventory"), 

#----------------------- Transfer Item --------------------

    path('transfer/',api.transfer, name="transfer"),
    path('transfer/<int:pk>/',api.transfer_from, name="transfer"),
    path('add_transfer/',api.add_transfer, name='add_transfer'),
    path('accept_transfer/',api.accept_transfer, name='accept_transfer'),
    path('transferlist/', api.transferlist, name="transferlist"),
    path('transfer-filter/<str:pk>/', api.transfer_filter, name="transfer_filter"),  


    path('quotation/add/',api.quatation, name="quatation"),  
    path('quatation-list/<str:pk>/',views.quatation_list, name="quatation-ist"),  
    path('add_quatation/',api.add_quatation, name='add_quatation'),   
    path('quotation/', api.quatationlist, name="quatationlist"),
    path("quatation-status-change/<int:pk>/",api.quatation_status_change, name = 'quatation-status-change') ,
    path('update_quotation_status/', api.update_quotation_status_api, name='update_quotation_status'),
  
#----------------------- Site Stocks ----------------------

    path('sitestock/',api.sitestock, name="sitestock"),
    path('update-site-stock' ,api.site_stock_update,name='site-stock-update'),

    path('viewstock/',api.viewstock, name="viewstock"),
 
#------------------------- Sub Contractor List --------------------

    path('subcontadd/',api.subcontadd, name="subcontadd"),
    path('add_subcontadd/', api.add_subcontadd, name='add_subcontadd'),
    path('subcontractorlist/',api.subcontractorlist, name="subcontractorlist"),
    path('subcontractorview/<int:pk>/', api.get_subcontractor, name='subcontractorview'),
    path('update_subcontractor/<int:pk>/', api.update_subcontractor, name='update_subcontractor'),
    path('delete_subcontractor/<int:pk>/', api.delete_subcontractor, name='delete_subcontractor'),
    path('update_status/', api.update_status, name='update_status'),
#---------------------------------------------------------------------- End Dharshini ------------------------------------------------------------------

#------------------------------------------------------------------------- Azar -----------------------------------------------------------------------

#----------- material library ---------------------------

    path('material-library/', api.material_library, name='material-library'),
    # api
    path('add_material-library/', api.add_material_library, name='add_material-library'),
    path('update_material-library/<int:pk>/', api.update_material_library, name='update_material-library'),
    path('material-library/<int:pk>/', api.delete_material_library, name='material-library'),


    #---------------------------------------------------- category ------------------------------------------------------------

    path('contract-category/', views.contract_category, name='contractcategory'),
    path('add-contract-category/', views.add_contract_category, name='add-contract-category'),
    path('update-contract-category/<int:pk>/', views.update_contract_category, name='update-contract-category'),
    path('contract-category/<int:pk>/', views.delete_contract_category, name='delete-contract-category'),

#----------------------------------------------------Contractor-------------------------------------------------------------

    path('contractor/', views.contractor, name='contractor'),
    path('add-contractor/', views.add_contractor, name='add-contractor'),
    path('update-contractor/<int:pk>/', views.update_contractor, name='update-contractor'),
    path('delete-contractor/<int:pk>/', views.delete_contractor, name='delete-contractor'),

    # project category  
    # render
    path('project-category/', api.project_category, name='project-category'), 
    #path('project-category/', views.procategory, name='project-category'), 
  
    # api
    path('add_project-category/', api.add_project_category, name='add_project-category'),
    path('update_project-category/<int:pk>/', api.update_project_category, name='update_project-category'),
    path('delete_project-category/<int:pk>/', api.delete_project_category, name='delete_project-category'),

    # project
    path('project/', api.project, name='project'), 
    path('project/<str:filter_by>/', api.project, name='project_filtered'), 


    # api
    path('add_project/', api.add_project, name='add_project'), 
    path('update_project/<int:pk>/', api.update_project, name='update_project'),
    path('delete_project/<int:id>/', api.delete_project, name='delete_project'),
    path('enable_project/<int:id>/', api.enable_project, name='enable_project'),
    # path('delete_employee/<int:id>/', views.delete_employee, name='delete_employee'),
    path('update_projectstatus/', api.update_projectstatus, name='update_projectstatus'),

    path('attendance/subcontract',views.attendancereport,name= 'proattendance'),
    path('add_attendance/', views.add_attendancereport, name='add_attendance'),
    path('update_attendancereport/<int:pk>/', views.update_attendancereport, name='update_attendancereport'),
    path('delete_attendancereport/<int:pk>/', views.delete_attendancereport, name='delete_attendancereport'),
    # path('attendancelist/<int:pk>/', views.attendancelist, name='attendancelist'),

constructionpro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('plotsale/', include('plotsale.urls')),
    path('auth/',include('app.auth_urls')),
]

app/forms.py
from .models import *
from django import forms
from .serializer import *
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator
from .models import ProjectCategory,Uom,EmpRoles,Employee,VendorRegistration

#-------------------------------------------------------------------- Dharshini ----------------------------------------------------------------

#------------------------------------------------------------- Custom User -------------------------------------------------------------

# class LoginForm(forms.Form):
#     email = forms.CharField(widget=forms.EmailInput)
#     password = forms.CharField(widget=forms.PasswordInput)

# class LoginForm(forms.Form):
#     email = forms.CharField(widget=forms.EmailInput, required=False)
#     phone_number = forms.CharField(required=False)
#     password = forms.CharField(widget=forms.PasswordInput)

#     def clean(self):
#         cleaned_data = super().clean()
#         email = cleaned_data.get("email")
#         phone_number = cleaned_data.get("phone_number")
        
#         if not email and not phone_number:
#             raise forms.ValidationError("Please enter either an email or a phone number.")
        
#         return cleaned_data

# class LoginForm(forms.Form):
#     identifier = forms.CharField(label='Email or Phone Number')
#     password = forms.CharField(widget=forms.PasswordInput)

#     def clean(self):
#         cleaned_data = super().clean()
#         identifier = cleaned_data.get("identifier")
        
#         if not identifier:
#             raise forms.ValidationError("Please enter either an email or a phone number.")
        
#         return cleaned_data

class LoginForm(forms.Form):
    identifier = forms.CharField(label='Email or Phone Number')
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_identifier(self):
        identifier = self.cleaned_data.get("identifier")

        if not identifier:
            raise forms.ValidationError("Please enter either an email or a phone number.")
        
        try:
            validate_email(identifier)
            is_email = True
        except ValidationError:
            is_email = False

        if not is_email:
            if not identifier.isdigit() or len(identifier) != 10:  # Assuming phone numbers are 10 digits
                raise forms.ValidationError("Please enter a valid phone number or email address.")

        return identifier



#------------------------------------------------------------- Company Staff -------------------------------------------------------------

class EmpRolesForm(forms.ModelForm):
    class Meta:
        model = EmpRoles
        fields = ['name','description']

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name','role','address','bankname','branch','bankaccount','ifsccode']



#-------------------------------------------------------------------- End Dharshini ----------------------------------------------------------------

class RegistrationForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    name = forms.CharField(max_length=255 ,required=True)
    phone_number = forms.CharField(max_length=10 ,required=True)
    address = forms.CharField(max_length=255,required=True)
    proof = forms.FileField(required=True)  # Add the file field for proof document upload

    company_email = forms.EmailField(required=True)
    company_name = forms.CharField(max_length=255 ,required=True)
    company_phone_number = forms.CharField(max_length=10 ,required=True)
    company_address = forms.CharField(max_length=255,required=True)

    class Meta:
        model = CustomUser
        fields = ['email', 'name', 'phone_number', 'address', 'proof' , "company_email","company_name","company_phone_number","company_address"]
class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=254)


class SetPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")

        if new_password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        return cleaned_data

app/templates/note.html
<span class="file-span"> <a  target="_blank" href="{{ i.modeldesign.url}}" >{{i.modeldesign |filename }}</a></span>


requiredKeys.forEach(function (key) {
    var value = formData.get(key);
    if (value === null || value === undefined || value === '') {
        isValid = false;
        errors[key] = ['This field may not be blank.'];
    } else if (!value.trim()) {
        isValid = false;
        errors[key] = ['This field may not be blank.'];
    }
})




  <!-- {% block header2 %}    {% endblock header2 %} -->





<div id="pagination-container"></div>

<div class="row">
    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_contractor_name"
            class="form-label">Contractor Name
            :</label>
        <input type="text" name="name" class="form-control"
            id="name">
        <span id="contractor_nameError"
            class="error-message"></span>
    </div>

    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_contact_no"
            class="form-label">Contact No
            :</label>
        <input type="number" name="contact_no"
            class="form-control" id="contact_no">
        <span id="contact_noError"
            class="error-message"></span>

    </div>

    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_address"
            class="form-label">Address</label>
        <input type="text" name="address"
            class="form-control" id="address">
        <span id="addressError"
            class="error-message"></span>
    </div>


    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="category"
            class="form-label mt-2">Category Name:</label>
        <select class="form-select" id="{{ i.id }}_category"
            name="category">
            <option value=""> ------- </option>
            <!-- Populate options with categories from your database -->
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
                
            {% endfor %}
        </select>
        <span id="categoryError"
            class="error-message"></span>

    </div> 


    <!-- <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_area" class="form-label mt-2">Area in
            Sqrt
            :</label>
        <input type="text" name="area" class="form-control"
            id="area">
        <span id="areaError" class="error-message"></span>

    </div> -->

    <hr>

    <div class="col-md-6 mt-2">
        <label for="{{ i.id }}_unit"
            class="form-label">Select Unit:</label>
        <select class="form-select" id="unit" name="unit">
            <option value="{{i.unit.id}}">{{i.unit.name}}</option>
            {% for unit in uom %}
                <option value="{{ unit.id }}">{{ unit.name }}</option>
            {% endfor %}
        </select>
        <span id="unitError" class="error-message"></span>
    </div>


    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_area" class="form-label mt-2">Rate
            :</label>
        <input type="text" name="rate" class="form-control"
            id="rate">
        <span id="rateError" class="error-message"></span>

    </div>

    <!-- <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_amount"
            class="form-label mt-2">Amount:</label>
        <input type="number" name="amount"
            class="form-control" id="amount">
        <span id="amountError" class="error-message"></span>

    </div> -->

    <hr>

    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_maistry"
            class="form-label mt-2">Maistry
            :</label>
        <input type="number" name="maistry"
            class="form-control" id="maistry">
        <span id="maistryError"
            class="error-message"></span>
    </div>

    <div class="col-lg-4 col-md-4 col-xs-6 col-12"></div>

    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_maison_cooli"
            class="form-label mt-2">Maison cooli
            :</label>
        <input type="number" name="maison_cooli"
            class="form-control" id="maison_cooli">
        <span id="maison_cooliError"
            class="error-message"></span>

    </div>

    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_male_skilled"
            class="form-label mt-2">Male Skilled
            :</label>
        <input type="number" name="male_skilled"
            class="form-control" id="male_skilled" required>
        <span id="male_skilledError"
            class="error-message"></span>
    </div>

    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_male_unskilled"
            class="form-label mt-2">Male
            Unskilled:</label>
        <input type="number" name="male_unskilled"
            class="form-control" id="male_unskilled"
            required>
        <span id="male_unskilledError"
            class="error-message"></span>
    </div>

    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_female_skilled"
            class="form-label mt-2">Female Skilled
            :</label>
        <input type="number" name="female_skilled"
            class="form-control" id="female_skilled"
            required>
        <span id="female_skilledError"
            class="error-message"></span>
    </div>

    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="id_female_unskilled"
            class="form-label mt-2">Female
            Unskilled</label>
        <input type="number" name="female_unskilled"
            class="form-control" id="female_unskilled"
            required>
        <span id="female_unskilledError"
            class="error-message"></span>
    </div>


    <!-- <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="category"
            class="form-label mt-2">Category Name:</label>
        <select class="form-select" id="{{ i.id }}_category"
            name="category">
            <option value=""> ------- </option>
           
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
                
            {% endfor %}
        </select>
        <span id="categoryError"
            class="error-message"></span>

    </div>  -->

    <div class="col-lg-4 col-md-4 col-xs-6 col-12">
        <label for="" class="form-label">Starting Date :</label>
        <input type="date" class="form-control" id="start_date"
          name="start_date">
        <span id="start_dateError" class="error-message"></span>

      </div>
    
    

</div>




<script>

    let activePage;

    // fetch url
    let fetchUrl = "profit-loss"

    // pagination
    const existingPaginationContainer = document.getElementById('pagination-container');

    // table
    const tableBody = document.querySelector('#example tbody');

    // filters 
    const firstDropdown = document.getElementById('filterdropdown1');
    const fromdate = document.getElementById('fromDate');
    // const todate = document.getElementById('toDate');

    var currentPage = 1;

    document.addEventListener('DOMContentLoaded', function () {

        // on dom loaded 
        const initialSelectedValue = firstDropdown.value;
        fetchData(1);

        // fetch table data API
        firstDropdown.addEventListener('change', function () {

            activePage = null
            fetchData(currentPage);
        });

        // todate.addEventListener('change', function () {
        //     activePage = null
        //     fetchData(currentPage);
        // });

        fromdate.addEventListener('change', function () {
            activePage = null
            fetchData(currentPage);
        });


    });


    // fetch data
    function fetchData(page) {

        if (activePage === page) {
            return
        }
        const selectedValue = firstDropdown?.value || 0;
        const from = fromdate?.value ? `${fromdate?.value}-15` : ""
        const to = ""
        try {
            fetch(`/${fetchUrl}/${selectedValue}/?page=${page}&salary_date=${from}&end_date=${to}`)
                .then(response => {
                    if (response.status === 200) {
                        console.log('Data fetched');
                        return response.json();
                    } else if (response.status === 404) {
                        throw new Error('Resource not found');
                    } else if (response.ok) {
                        throw new Error(`HTTP error! Status: ${response.status}`);
                    } else {
                        throw new Error('Network response was not ok');
                    }
                })
                .then(data => {
                    tableBody.innerHTML = '';
                    renderDataOrMessage(tableBody, data, page)
                    activePage = page
                })
                .catch(error => {
                    console.error('Error fetching data:', error);
                    showToast(errorAlertMessage?.message, '', errorAlertMessage?.bgColor);
                });
        } catch (error) {
            console.error('Error in fetch operation:', error);
        }
    }





    // MANIPULATE TABLE DATA
    function createTableRow(serialNumber, data) {

        const newRow = document.createElement('tr');
        newRow.setAttribute('data-item-id', data.id);

        const idCell = createSerialCell(serialNumber);
        newRow.appendChild(idCell);

        // const td2 = createTableCell(get_value(data.created_at));
        // newRow.appendChild(td2);

        const td3 = createTableCell(get_value(data.name));
        newRow.appendChild(td3);

        const td4 = createTableCell(get_value(data.start_date));
        newRow.appendChild(td4);

        const td5 = createTableCell(get_value(data.end_date));
        newRow.appendChild(td5);

        const td6 = createAmountCell(get_value(data.salary));
        newRow.appendChild(td6);

        // const td7 = createTableCell(get_value(data.pending));
        // newRow.appendChild(td7);



        // actioncell
        const actionCell = createPayActionCell('invoiceHistoryModalAdd');
        newRow.appendChild(actionCell);

        // click event
        actionCell.addEventListener('click', () => {
            populateModalData(data)
        });

        return newRow;
    }




    // nested table
    function populateModalData(data) {
        const form = document.getElementById('dataEditForm');
        if (!form) {
            console.error("Form element not found.");
            return;
        }

        setModalInputValue(form, 'name', data.name);
        setModalInputValue(form, 'payment_period_start', data.start_date);
        setModalInputValue(form, 'payment_period_end', data.end_date);
        // alert(data.paid_amount)
        setModalInputValue(form, 'amount', data.salary);

        // setModalInputValue(form, 'hidden_paid_amount', data.paid_amount);

        setModalInputValue(form, 'paid', data.paid);
        setModalInputValue(form, 'pending', data.pending);
       
 

        const saveButton = form.querySelector('#saveButton');
        if (saveButton) {
            saveButton.setAttribute("data-id", data.id);
        } else {
            console.error("Save button not found in the form.");
        }

    }




</script>

app/templates/pagination.html
{% load static %}




<div> 
 
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if queryset.has_previous %}
            <li class="page-item"><a class="page-link" href="?search={{ request.GET.search }}&page={{ queryset.previous_page_number }}">Previous</a></li>
           
            {% endif %}

            {% for num in queryset.paginator.page_range %}


             {% if  queryset.paginator.num_pages == 1 %}


             {% else %}
            
              {% if queryset.number == num %}
              <!-- <span class="current">{{ num }}</span> -->
              <li class="page-item active" >   <a class="page-link" href="?search={{ request.GET.search }}&page={{ num }}">{{ num }} </a> </li>
              {% else %}
              <li class="page-item">   <a class="page-link" href="?search={{ request.GET.search }}&page={{ num }}">{{ num }}</a> </li>
              {% endif %}

              {% endif %}


            {% endfor %}

          {% if queryset.has_next %}
          <li class="page-item"><a class="page-link"  href="?search={{ request.GET.search }}&page={{ queryset.next_page_number }}" >Next</a></li>
          {% endif %}
        </ul>
      </nav>
</div>

app/templates/search.html
{% load static %}

<!-- <form method="GET" action="{% url location %}">
    <div class="row mb-3">
        <div class="col-4">
            <input type="text" class="form-control" name="search" placeholder="Search..." value="{{search}}">
        </div>
        <div class="col">
            <button type="submit" class='btn btn-soft-secondary '>
                {% if search %}
                Clear
                {% else %}
                Search
                {% endif %}
            </button>
        </div>
    </div>

</form> -->



<style>
    .input-container {
        position: relative;
    }
    .clear-btn {
        position: absolute;
        right: 20px;
        top: 50%;
        transform: translateY(-50%);
        cursor: pointer;
        /* visibility: hidden; */
        /* padding: 0 5px; */
        background-color: transparent;
        border: none;
        height: max-content;
    }
    .input-container:hover .clear-btn {
        visibility: visible;
    }
</style>

<form id="searchForm" method="GET" action="{% url location %}">
    <div class="row mb-3">
        <div class="col-4 input-container">
            <input id="searchInput" type="text" class="form-control" name="search" placeholder="Search..." value="{{ search }}">
            <button id="clearSearch" class="clear-btn " type="button" onclick="clearInput()">&times;</button>
        </div>
        <div class="col">
            <button type="submit" class='btn btn-soft-secondary'>
             
                    Search
       
            </button>
        </div>
    </div>
</form>



<script>
    document.addEventListener('DOMContentLoaded', function() {
        const searchInput = document.getElementById('searchInput');
        const searchForm = document.getElementById('searchForm');
        const clearButton = document.getElementById('clearSearch');

        // Add click event listener to the clear button
        clearButton.addEventListener('click', function() {
            searchInput.value = ''; // Clear the search input
            const urlWithoutSearchParam = window.location.href.split('?')[0];
            window.location.href = urlWithoutSearchParam; // Reload the page without the query parameter
        });

        // Add submit event listener to the form
        searchForm.addEventListener('submit', function(e) {
            // Prevent the default form submission
            e.preventDefault();

            // Check if the input value is not empty
            if (searchInput.value.trim()) {
                searchForm.submit(); // Submit the form normally
            } else {
                const urlWithoutSearchParam = window.location.href.split('?')[0];
                window.location.href = urlWithoutSearchParam; // Reload the page without the query parameter
            }
        });
    });



    function clearInput (){
            searchInput.value = ''; // Clear the search input
            const urlWithoutSearchParam = window.location.href.split('?')[0];
            window.location.href = urlWithoutSearchParam; // Reload the page without the query parameter
    }
</script>